name: blinkoo_web_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  intl: 0.20.1
  easy_localization: ^3.0.7                 # Localization library        


  # Dependency Injection
  injectable: ^2.4.2
  get_it: ^8.0.2

  # HTTP
  dio: ^5.4.1

  # Database
  hydrated_bloc: ^9.0.0

  # Utilities
  audio_video_progress_bar: ^2.0.2          # Video progress bar
  azure_application_insights: ^4.0.1        # Application insights library
  carousel_slider_plus: ^7.0.0              # A carousel slider widget
  carousel_slider: ^5.0.0                   # A carousel slider widget
  collection: ^1.17.1                       # Collections and utilities functions and classes related to collections (Cannot be updated due to flutter_test)
  device_info_plus: ^11.1.1                 # Provides detailed information about the device
  dynamic_color: ^1.7.0                     # Create material color schemes based on platform's implementation of dynamic color
  expressions: ^0.2.5+1                     # Dynamic expression evaluator
  flutter_bloc: ^8.1.1                      # Provides widgets used to implement the BLoC pattern
  flutter_html: 3.0.0-beta.2                # Render static html and css (NOT UPDATE 'TILL IS NOT OUTSIDE OF BETA)
  flutter_svg: ^2.0.10+1                    # Draw SVG files on a Flutter Widget
  http: ^1.1.2                              # Future-based API for HTTP requests (CANNOT BE UPDATED: Google Place dependency)
  logger: ^2.1.0                            # Logger inspired by Logger for Android
  json_annotation: ^4.8.1                   # Support for JSON code generation via the `json_serializable` package
  material_color_utilities: ^0.12.0         # Material color utilities
  mutex: ^3.0.0                             # Mutual exclusion with implementation of normal and read-write mutex
  package_info_plus: ^8.0.0                 # Get Package information
  rive: ^0.13.9                             # For Rive animation integration
  rxdart: ^0.28.0                           # Extends the capabilities of Dart Streams and StreamControllers
  share_plus: ^10.0.2                       # Flutter plugin for sharing content
  shared_preferences: ^2.0.15               # Reading and writing simple key-value pairs
  timeago: ^3.6.0                           # For creating fuzzy timestamps
  uuid: ^4.2.1                              # UUID generator
  video_player:                             # Flutter plugin for displaying inline video
    git:
      url: https://github.com/blinkoo-it/flutter-video-player
      path: video_player/video_player
      ref: 2.8.6+9
  video_player_web_hls:                     # Flutter plugin for displaying inline video with HLS support
    git:
      url: https://github.com/blinkoo-it/flutter-video-player
      path: video_player_web_hls
      ref: 2.8.6+9

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^6.7.0

  # Linter
  flutter_lints: ^5.0.0

  # Dependency Injection
  injectable_generator: ^2.6.1
  build_runner: ^2.4.7

  # Assets Generator
  flutter_gen_runner: ^5.5.0+1

  # Automatically generate code for converting to and from JSON
  json_serializable: ^6.7.1

dependency_overrides:
  analyzer: ^6.7.0
  dart_style: ^2.3.4
  intl: ^0.20.1
  http: ^1.2.2
  material_color_utilities: 0.12.0
  path: ^1.9.0
  rxdart: ^0.28.0
  uuid: ^4.5.0
  web: ^1.0.0
  # device_info_plus_platform_interface: 7.0.3

flutter:
  generate: true
  uses-material-design: true

  # Assets
  assets:
    - assets/svgs/
    - assets/flags/
    - assets/animations/
    - assets/translations/
    - pubspec.yaml

  #Fonts
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
    - family: BlinkooIconFont
      fonts:
        - asset: assets/fonts/blinkoo_icons/BlinkooIconFont.ttf
